# Generated by Django 6.0.3 on 2026-04-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(default='students.csv', max_length=255)),
                ('rows_extracted', models.IntegerField(default=0)),
                ('rows_loaded', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=20)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'ETL Log',
                'verbose_name_plural': 'ETL Logs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('full_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clean Student Record',
                'verbose_name_plural': 'Clean Student Records',
            },
        ),
        migrations.CreateModel(
            name='StudentRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Student Record',
                'verbose_name_plural': 'Raw Student Records',
            },
        ),
    ]
